### ISSUE TITLE
Marking mail moves it to cur unconditionally

### ISSUE THREAD

**Issue by ap** [xantronix/Mail-Dir#2]
I don’t know if this is right in the first place; it seems this should have been written to leave the mail wherever it is.

What I do know is Mutt makes a distinction between non-`S`-flagged mail in `new` (which it considers really unread) vs non-`S`-flagged mail in `cur` (which it considers seen-but-not-read). It *can* mark unread mail as seen-but-not-read (i.e. move it from `new` to `cur`) without adding an `S` flag, but the user can configure it not to.

I’m not sure what the right thing is, or how to proceed.

**Comment by ap** [comment]
One option I thought of, given the circumstances, is to add an optional second argument to `->mark`, which may be `cur` or `new` to specify the target explicitly, or just a `1` to say “leave it wherever it was”. If the argument is false or missing, the mail is moved to `cur` as usual.

**Comment by xantronix** [comment]
I thought about this one, and I can't quite think of any problems allowing one to specify {cur,tmp,new} explicitly, since it doesn't break any default behaviors described by DJB's Maildir specification. Once again, I definitely appreciate your patch and your patronage of my stupid module!

**Comment by ap** [comment]
Good enough for me! I wasn’t in the mood for the dep chains of just about all the other modules that do Maildir delivery, and I was hoping not to have to write and maintain this code myself; your stupid module fit the bill perfectly.
